<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <joint name="camera_joint" type="fixed">
      <parent link="chassis"/>
      <child link="camera_link"/>
      <origin xyz="${(chassis_length+head_length)/2} 0.0 ${chassis_height + (head_height * 0.8)}"/>
   </joint>

   <link name="camera_link">
      <visual>
         <origin xyz="${0.005/2} 0 0" rpy="0 ${pi/2} 0"/>
         <geometry>
            <cylinder radius="0.0105" length="0.005"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="${0.005/2} 0 0" rpy="0 ${pi/2} 0"/>
         <geometry>
            <cylinder radius="0.0105" length="0.005"/>
         </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.093" length="0.005" radius="0.0105">
         <origin xyz="${0.005/2} 0 0" rpy="0 ${pi/2} 0"/>
      </xacro:inertial_cylinder>
   </link>
   
   <joint name="camera_joint_optical" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_link_optical"/>
      <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
   </joint>

   <link name="camera_link_optical"></link>

   <gazebo reference="camera_link">
      <material>Gazebo/Black</material>
      <sensor name="camera" type="camera">
         <pose>0 0 0 0 0 0</pose>
         <visualize>true</visualize>
         <update_rate>24</update_rate>
         <camera>
            <horizontal_fov>1.5708</horizontal_fov>
            <image>
               <width>1280</width>
               <height>720</height>
               <format>R8G8B8</format>
            </image>
            <clip>
               <near>0.05</near>
               <far>8.0</far>
            </clip>
         </camera>
         <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <frame_name>camera_link_optical</frame_name>
         </plugin>
      </sensor>
   </gazebo>

</robot>