<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- CHASSIS -->
   <xacro:property name="chassis_length" value="0.170"/>
   <xacro:property name="chassis_width" value="0.275"/>
   <xacro:property name="chassis_height" value="0.36"/>
   <xacro:property name="chassis_mass" value="3.0"/>

   <!-- HEAD -->
   <xacro:property name="head_length" value="0.230"/>
   <xacro:property name="head_width" value="0.385"/>
   <xacro:property name="head_height" value="0.220"/>
   <xacro:property name="head_mass" value="0.425"/>

      <!-- FRONT CASTER PLATFORM -->
   <xacro:property name="front_caster_holder_length" value="0.160"/>
   <xacro:property name="front_caster_holder_width" value="0.085"/>
   <xacro:property name="front_caster_holder_height" value="0.050"/>
   <xacro:property name="front_caster_holder_mass" value="0.35"/>

   <!-- BACK CASTER PLATFORM -->
   <xacro:property name="back_wheel_holder_length" value="0.040"/>
   <xacro:property name="back_wheel_holder_width" value="0.090"/>
   <xacro:property name="back_wheel_holder_height" value="0.009"/>
   <xacro:property name="back_wheel_holder_mass" value="0.2235"/>

   <!-- WHEELS -->
   <xacro:property name="wheel_radius" value="0.04"/>
   <xacro:property name="wheel_thickness" value="0.035"/>
   <xacro:property name="wheel_mass" value="0.15"/>
   <xacro:property name="wheel_offset_x" value="${(chassis_length + back_wheel_holder_length)/2}"/>
   <xacro:property name="wheel_offset_y" value="${(chassis_width+wheel_thickness)/2}"/>
   <xacro:property name="wheel_offset_z" value="0.035"/>

   <!-- CASTER WHEELS -->
   <xacro:property name="caster_wheel_radius" value="0.04"/>
   <xacro:property name="caster_wheel_mass" value="0.1"/>
   <xacro:property name="caster_wheel_offset_x" value="${front_caster_holder_length - 0.04}"/>
   <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

   <!-- COLORS -->
   <material name="white">
      <color rgba="1 1 1 1"/>
   </material>

   <material name="black">
      <color rgba="0 0 0 1"/>
   </material>

   <material name="grey" >
        <color rgba="0.5725490196078431 0.5843137254901961 0.5686274509803921 1.0" />
    </material>

   <material name="bloodorange" >
    <color rgba="0.996078431372549 0.29411764705882354 0.011764705882352941 1.0" />
  </material>

</robot>