<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://wiki.ros.org/wiki/xacro">

   <xacro:include filename="inertial_macros.xacro"/>

   <xacro:property name="chassis_length" value="0.170"/>
   <xacro:property name="chassis_width" value="0.275"/>
   <xacro:property name="chassis_height" value="0.36"/>
   <xacro:property name="chassis_mass" value="2.5"/>
   <xacro:property name="head_length" value="0.230"/>
   <xacro:property name="head_width" value="0.385"/>
   <xacro:property name="head_height" value="0.220"/>
   <xacro:property name="head_mass" value="0.7"/>
   <xacro:property name="front_caster_holder_length" value="0.160"/>
   <xacro:property name="front_caster_holder_width" value="0.085"/>
   <xacro:property name="front_caster_holder_height" value="0.050"/>
   <xacro:property name="front_caster_holder_mass" value="0.08"/>
   <xacro:property name="back_wheel_holder_length" value="0.05"/>
   <xacro:property name="back_wheel_holder_width" value="0.1"/>
   <xacro:property name="back_wheel_holder_height" value="0.02"/>
   <xacro:property name="back_wheel_holder_mass" value="0.05"/>
   <xacro:property name="wheel_radius" value="0.04"/>
   <xacro:property name="wheel_thickness" value="0.035"/>
   <xacro:property name="wheel_mass" value="0.15"/>
   <xacro:property name="wheel_offset_x" value="0.11"/>
   <xacro:property name="wheel_offset_y" value="0.1375"/>
   <xacro:property name="wheel_offset_z" value="0.030"/>
   <xacro:property name="caster_wheel_radius" value="0.04"/>
   <xacro:property name="caster_wheel_mass" value="0.1"/>
   <xacro:property name="caster_wheel_offset_x" value="0.120"/>
   <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
   
   <material name="white">
      <color rgba="1 1 1 1"/>
   </material>

   <material name="black">
      <color rgba="0 0 0 1"/>
   </material>

   <material name="grey" >
        <color rgba="0.5725490196078431 0.5843137254901961 0.5686274509803921 1.0" />
    </material>

   <!-- BASE LINK -->
   <link name="base_link"></link>

   <!-- CHASSIS -->
   <joint name="chassis_joint" type="fixed">
      <origin xyz="-${chassis_length/2} 0.0 0.0"/>
      <parent link="base_link"/>
      <child link="chassis"/>
   </joint>
   
   <link name="chassis">
      <visual>
         <origin xyz="${chassis_length/2} 0.0 ${chassis_height/2}"/>
         <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
         </geometry>  
         <material name="white"/> 
      </visual>
      <collision>
         <origin xyz="0.085 0.0 0.18"/>
         <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
         </geometry>  
      </collision>
      <xacro:inertial_box mass="2" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
         <origin xyz="${chassis_length} 0.0 ${chassis_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <gazebo reference="chassis">
      <material>Gazebo/White</material>
   </gazebo>

   <joint name="head_joint" type="fixed">
      <origin xyz="0.0 0.0 ${chassis_height + (head_height/2)}"/>
      <parent link="base_link"/>
      <child link="head"/>
   </joint>
   
   <link name="head">
      <visual>
         <origin xyz="0.0 0.0 0.0"/>
         <geometry>
            <box size="${head_length} ${head_width} ${head_height}"/>
         </geometry>   
         <material name="white"/> 
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0"/>
         <geometry>
            <box size="${head_length} ${head_width} ${head_height}"/>
         </geometry>
      </collision>
      <xacro:inertial_box mass="2" x="${head_length}" y="${head_width}" z="${head_height}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <gazebo reference="head">
      <material>Gazebo/White</material>
   </gazebo>

   <joint name="front_caster_holder_joint" type="fixed">
      <origin xyz="${chassis_length} 0.0 0.0"/>
      <parent link="chassis"/>
      <child link="front_caster_holder"/>
   </joint>

   <link name="front_caster_holder">
      <visual>
         <origin xyz="${front_caster_holder_length/2} 0.0 ${front_caster_holder_height/2}"/>
         <geometry>
            <box size="${front_caster_holder_length} ${front_caster_holder_width} ${front_caster_holder_height}"/>
         </geometry>  
         <material name="white"/> 
      </visual>
      <collision>
         <origin xyz="${front_caster_holder_length/2} 0.0 ${front_caster_holder_height/2}"/>
         <geometry>
            <box size="${front_caster_holder_length} ${front_caster_holder_width} ${front_caster_holder_height}"/>
         </geometry>    
      </collision>
      <xacro:inertial_box mass="${front_caster_holder_mass}" x="${front_caster_holder_length}" y="${front_caster_holder_width}" z="${front_caster_holder_height}">
         <origin xyz="${front_caster_holder_length/2} 0.0 ${front_caster_holder_height/2}"/>
      </xacro:inertial_box>
   </link>

   <gazebo reference="front_caster_holder">
      <material>Gazebo/White</material>
   </gazebo>

   <joint name="left_back_wheel_holder_joint" type="fixed">
      <origin xyz="0.0 ${chassis_width/2} 0.0"/>
      <parent link="chassis"/>
      <child link="left_back_caster_holder"/>
   </joint>

   <link name="left_back_caster_holder">
      <visual>
         <origin xyz="-${back_wheel_holder_length/2} -${back_wheel_holder_width/2} ${back_wheel_holder_height/2}"/>
         <geometry>
            <box size="${back_wheel_holder_length} ${back_wheel_holder_width} ${back_wheel_holder_height}"/>
         </geometry>  
         <material name="white"/> 
      </visual>
      <collision>
         <origin xyz="-${back_wheel_holder_length/2} -${back_wheel_holder_width/2} ${back_wheel_holder_height/2}"/>
         <geometry>
            <box size="${back_wheel_holder_length} ${back_wheel_holder_width} ${back_wheel_holder_height}"/>
         </geometry>   
      </collision>
      <xacro:inertial_box mass="${back_wheel_holder_mass}" x="${back_wheel_holder_length}" y="${back_wheel_holder_width}" z="${back_wheel_holder_height}">
         <origin xyz="-${back_wheel_holder_length/2} -${back_wheel_holder_width/2} ${back_wheel_holder_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <gazebo reference="left_back_caster_holder">
      <material>Gazebo/White</material>
   </gazebo>

   <joint name="right_back_caster_holder_joint" type="fixed">
      <origin xyz="0.0 -${chassis_width/2} 0.0"/>
      <parent link="chassis"/>
      <child link="right_back_caster_holder"/>
   </joint>

   <link name="right_back_caster_holder">
      <visual>
         <origin xyz="-${back_wheel_holder_length/2} ${back_wheel_holder_width/2} ${back_wheel_holder_height/2}"/>
         <geometry>
            <box size="${back_wheel_holder_length} ${back_wheel_holder_width} ${back_wheel_holder_height}"/>
         </geometry>  
         <material name="white"/> 
      </visual>
      <collision>
         <origin xyz="-${back_wheel_holder_length/2} ${back_wheel_holder_width/2} ${back_wheel_holder_height/2}"/>
         <geometry>
            <box size="${back_wheel_holder_length} ${back_wheel_holder_width} ${back_wheel_holder_height}"/>
         </geometry>    
      </collision>
      <xacro:inertial_box mass="${back_wheel_holder_mass}" x="${back_wheel_holder_length}" y="${back_wheel_holder_width}" z="${back_wheel_holder_height}">
         <origin xyz="-${back_wheel_holder_length/2} ${back_wheel_holder_width/2} ${back_wheel_holder_height/2}" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
   </link>

   <gazebo reference="right_back_caster_holder">
      <material>Gazebo/White</material>
   </gazebo>

   <!-- WHEELS -->

   <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel"/>
      <origin xyz="-${wheel_offset_x} ${wheel_offset_y} -${wheel_offset_z}" rpy="-${pi/2} 0 0"/>
      <axis xyz="0.0 0.0 1"/>
   </joint>

   <link name="left_wheel">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
         </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
   </gazebo>

   <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel"/>
      <origin xyz="-${wheel_offset_x} -${wheel_offset_y} -${wheel_offset_z}" rpy="${pi/2} 0 0"/>
      <axis xyz="0.0 0.0 -1"/>
   </joint>

   <link name="right_wheel">
      <visual>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
         </geometry>
      </collision>
       <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
   </gazebo>

   <!-- CASTER WHEELS -->
   <joint name="front_caster_wheel_joint" type="fixed">
      <parent link="front_caster_holder"/>
      <child link="front_caster_wheel"/>
      <origin xyz="${caster_wheel_offset_x} 0.0 -${caster_wheel_offset_z}"/>
   </joint>

   <link name="front_caster_wheel">
      <visual>
         <origin xyz="0.0 0.0 0.0"/>
         <geometry>
            <sphere radius="${caster_wheel_radius}"/>
         </geometry>
         <material name="black"/>
      </visual>
      <collision>
         <origin xyz="0.0 0.0 0.0"/>
         <geometry>
            <sphere radius="${caster_wheel_radius}"/>
         </geometry>
      </collision>
      <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
         <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_sphere>
   </link>

   <gazebo reference="front_caster_wheel">
      <material>Gazebo/Black</material>
      <mu1 value="0.001"/>
      <mu2 value="0.001"/>

   </gazebo>


</robot>